apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: fraud-detection-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    type: HTTP
    requestPath: /ready_check
    port: 8000
