apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-service
  labels:
    app: fraud-detection-api
  annotations:
    cloud.google.com/backend-config: '{"default": "fraud-detection-backendconfig"}'
spec:
  type: LoadBalancer
  selector:
    app: fraud-detection-api
  ports:
    - protocol: TCP
      port: 80          # external port
      targetPort: 8000 
